// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ29zTvOGUmyhPKmYF0dcYvB50zB7Od_4',
    appId: '1:472958542373:web:971dcaa432ff81de6895cc',
    messagingSenderId: '472958542373',
    projectId: 'my-sales-app-b3506',
    authDomain: 'my-sales-app-b3506.firebaseapp.com',
    storageBucket: 'my-sales-app-b3506.firebasestorage.app',
    measurementId: 'G-YKP6YG25LZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-Iz77Q7zk5S14GPDITgV2eKbZnEDCxPU',
    appId: '1:472958542373:android:f3574f800e07f9776895cc',
    messagingSenderId: '472958542373',
    projectId: 'my-sales-app-b3506',
    storageBucket: 'my-sales-app-b3506.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2vGw2bSn51B6aIEOSZ-XVghwUoJmy0e4',
    appId: '1:472958542373:ios:d13ca64eebe10c606895cc',
    messagingSenderId: '472958542373',
    projectId: 'my-sales-app-b3506',
    storageBucket: 'my-sales-app-b3506.firebasestorage.app',
    iosBundleId: 'com.example.mySaleApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2vGw2bSn51B6aIEOSZ-XVghwUoJmy0e4',
    appId: '1:472958542373:ios:d13ca64eebe10c606895cc',
    messagingSenderId: '472958542373',
    projectId: 'my-sales-app-b3506',
    storageBucket: 'my-sales-app-b3506.firebasestorage.app',
    iosBundleId: 'com.example.mySaleApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQ29zTvOGUmyhPKmYF0dcYvB50zB7Od_4',
    appId: '1:472958542373:web:859c9e4d0c64a39e6895cc',
    messagingSenderId: '472958542373',
    projectId: 'my-sales-app-b3506',
    authDomain: 'my-sales-app-b3506.firebaseapp.com',
    storageBucket: 'my-sales-app-b3506.firebasestorage.app',
    measurementId: 'G-K4TVL6Y1RL',
  );
}
